name: project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  ionicons: ^0.2.2
  http: ^1.1.0
  google_maps_flutter: ^2.3.0
  flutter_calendar_carousel: ^2.4.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  provider: ^6.0.5
  abushakir: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/
